language: objective-c
osx_image: xcode7
script:
  - set -o pipefail && xcodebuild clean test -workspace ./src/src.xcworkspace -scheme srcTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Only build PRs and pushes to master
branches:
  only:
    - develop
