# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Demo' do
pod 'ringcentral', :git => 'https://github.com/anilkumarbp/ringcentral-swiftv2.0.git'
pod 'SwiftyJSON'
end

target 'DemoTests' do

end

target 'DemoUITests' do

end

