# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'src' do
pod 'PubNub', '~>4.0'
pod 'CryptoSwift'
pod 'SwiftyJSON'
end

target 'srcTests' do

end

